function DevReset(){
    game = {
        points: 0,
        ppc: 1,
        unlocks: ["Unlock Prestige Points", "Unlock Prestige Powers", "Unlock Boosters", "Unlock Automation", "Unlock Ascension", "Unlock Allocation Points", "Unlock The Void", "Unlock Void Boosters", "Finish the game"],
        unlockCost: [10, 1000, 10 ** 8, 10 ** 13, 10 ** 18, 10 ** 28, 10 ** 45, 10 ** 50, 10 ** 300],
        unlockAmount: 7,
        prestigeGain: 0,
        prestigeAmount: 10 ** 10,
        upgamnt: 3,
        presupgamnt: 3,
        PU1: true,
        PU2: true,
        PU3: true,
        PU4: true,
        PU5: true,
        PU6: true,
        PU1applied: false,
        PU2applied: false,
        PU3applied: false,
        presupgcost: [1, 5, 10, 10 ** 15, 10 ** 19, 10 ** 21, 10 ** 300],
        presupg: ["PU1", "PU2", "PU3", "PU4", "PU5", "PU6", "end"],
        powerAmount: 10 ** 13,
        powerGain: 0,
        powerEffect: 1,
        powerEffectExp: 0.5,
        powB1: 10,
        powB2: 10,
        powB3: 10,
        powB1cost: 100,
        powB2cost: 500,
        powB3cost: 1000,
        powB1base: 2,
        powB2base: 2,
        powB3base: 2,
        powB1max: 10,
        powB2max: 10,
        powB3max: 10,
        powB1scaling: 2,
        powB2scaling: 5,
        powB3scaling: 10,
        powB1effect: 1,
        powB2effect: 1,
        powB3effect: 1,
        boosters: 5,
        boosterrequirement: 10 ** 9,
        boostereffect: 1,
        boosterreq: [1, 10**300],
        BM1: true,
        BM2: true,
        miles: 2,
        bstrmiles: 2,
        bstrupgamnt: 1,
        boostupgcost: [3, 4, 5],
        BU1: true,
        BU2: true,
        BU3: true,
        BU1effect: 4,
        BU2effect: 4,
        BU3effect: 4,
        AutoAmount: 10 ** 9,
        AutoGain: 0,
        PauseAuto: 2,
        PointAuto: 15,
        Presauto: 10,
        Powauto: 9,
        Autoauto: 0,
        autocost: [10, 1000, 10 ** 6, 10 ** 10],
        autoeff: [0, 0, 0, 0],
        QOLU: [true, true, true, true, true, true, true, false],
        QOLUBought: 4,
        AscAmount: 100,
        AscGain: 0,
        RankRequirement: [1, 2, 5, 25, 10 ** 300],
        RankEffect: ["Boost points by 10, Prestige by 5, Power by 3 and Ascension points by 2", "Keep 1 of each automation on ascension", "Unlock more Prestige upgrades and keep QOL I on Ascend", "Boost Ascension points based on Ranks and unlock some Ascension upgrades", "-"],
        RankLevel: 8,
        ifAscend: true,
        rank4reward: 1,
        rank4exp: 1,
        AscU1: true,
        AscU2: false,
        AscU3: false,
        ascupgamnt: 1,
        AscB1: [2, 1, 1, 1],
        APbuyables: [[4, 10 ** 44], [3, 1.56 * 10 ** 33], [3, 1.25 * 10 ** 28], [6, 409600]],
        APamount: [20, 1],
        APU: [[true, true, true], [true, true, true], [true, true, false]],
        InVoid: false,
        BestPoints: 0,
        VoidEnergy: [0, 1000, 1, 0],
        VoidPower: 10 ** 6,
        VoidBuyables: [[5, 10], [3, 100], [2, [1000, 100000, 10 ** 300]]],
        VB3cost: [1000, 100000, 10 ** 300],
        VoidEffect: [1, 1, 1, 1]
    };
    game.powerEffect = 1 + game.powerAmount ** 0.5;
    game.boostereffect = 2 ** game.boosters;
    game.boosterrequirement = (10 ** 9) * (10 ** (game.boosters ** 2))
    game.AscGain = game.boostereffect / game.boosters ** 2
    game.rank4reward = game.RankLevel
    calculatePPC();
    calculatePP();
    calculatePPow();
    updateTabs();
};
