function HardReset(){
    game = {
        points: 0,
        ppc: 1,
        unlocks: ["Unlock Prestige Points", "Unlock Prestige Powers", "Unlock Boosters", "Unlock Automation", "Unlock Ascension", "Unlock Allocation Points", "Finish the game"],
        unlockCost: [10, 1000, 10 ** 9, 10 ** 13, 10 ** 18, 10 ** 28, 10 ** 300],
        unlockAmount: 0,
        prestigeGain: 0,
        prestigeAmount: 0,
        upgamnt: 0,
        presupgamnt: 0,
        PU1: false,
        PU2: false,
        PU3: false,
        PU4: false,
        PU5: false,
        PU6: false,
        PU1applied: false,
        PU2applied: false,
        PU3applied: false,
        presupgcost: [1, 5, 10, 10 ** 15, 10 ** 19, 10 ** 21, 10 ** 300],
        presupg: ["PU1", "PU2", "PU3", "PU4", "PU5", "PU6", "end"],
        powerAmount: 0,
        powerGain: 0,
        powerEffect: 1,
        powerEffectExp: 0.5,
        powB1: 0,
        powB2: 0,
        powB3: 0,
        powB1cost: 100,
        powB2cost: 500,
        powB3cost: 1000,
        powB1base: 2,
        powB2base: 2,
        powB3base: 2,
        powB1max: 10,
        powB2max: 10,
        powB3max: 10,
        powB1scaling: 2,
        powB2scaling: 5,
        powB3scaling: 10,
        powB1effect: 1,
        powB2effect: 1,
        powB3effect: 1,
        boosters: 0,
        boosterrequirement: 10 ** 9,
        boostereffect: 1,
        boosterreq: [1, 10**300],
        BM1: false,
        BM2: false,
        miles: 0,
        bstrmiles: 0,
        bstrupgamnt: 0,
        boostupgcost: [3, 4, 5],
        BU1: false,
        BU2: false,
        BU3: false,
        BU1effect: 1,
        BU2effect: 1,
        BU3effect: 1,
        AutoAmount: 0,
        AutoGain: 0,
        PointAuto: 0,
        Presauto: 0,
        Powauto: 0,
        Autoauto: 0,
        autocost: [10, 1000, 10 ** 6, 10 ** 10],
        autoeff: [0, 0, 0, 0],
        pausedauto: false,
        QOLU: [false, false, false, false],
        QOLUBought: 0,
        AscAmount: 0,
        AscGain: 0,
        RankRequirement: [1, 2, 10, 100, 10 ** 300],
        RankEffect: ["Boost points by 10, Prestige by 5, Power by 3 and Ascension points by 2", "Keep 1 of each automation on ascension", "Unlock more Prestige upgrades and keep QOL I on Ascend", "Boost Ascension points based on Ranks and unlock some Ascension upgrades", "-"],
        RankLevel: 0,
        ifAscend: false,
        rank4reward: 1,
        rank4exp: 1,
        ascupgamnt: 0,
        AscB1: [0, 1, 1],
    };
    updateTabs();
};
