function HardReset(){
    game = {
        points: 0,
        ppc: 1,
        PointSoftcapStart: 10**50,
        PointSoftcapEffect: 0.4,
        unlocks: ["Unlock Prestige Points", "Unlock Prestige Powers", "Unlock Boosters", "Unlock Automation", "Unlock Ascension", "Unlock Allocation Points", "Unlock The Void", "Unlock Void Boosters", "Unlock The Beacon" ,"Finish the game"],
        unlockCost: [10, 1000, 10 ** 8, 10 ** 13, 10 ** 18, 10 ** 28, 10 ** 45, 10 ** 60, 10 ** 80, 10 ** 300],
        unlockAmount: 0,
        prestigeGain: 0,
        prestigeAmount: 0,
        upgamnt: 0,
        presupgamnt: 0,
        PU1: false,
        PU2: false,
        PU3: false,
        PU4: false,
        PU5: false,
        PU6: false,
        PU1applied: false,
        PU2applied: false,
        PU3applied: false,
        presupgcost: [1, 5, 10, 10 ** 15, 10 ** 19, 10 ** 21, 10 ** 300],
        presupg: ["PU1", "PU2", "PU3", "PU4", "PU5", "PU6", "end"],
        powerAmount: 0,
        powerGain: 0,
        powerEffect: 1,
        powerEffectExp: 0.5,
        powB1: 0,
        powB2: 0,
        powB3: 0,
        powB1cost: 100,
        powB2cost: 500,
        powB3cost: 1000,
        powB1base: 2,
        powB2base: 2,
        powB3base: 2,
        powB1max: 10,
        powB2max: 10,
        powB3max: 10,
        powB1scaling: 2,
        powB2scaling: 5,
        powB3scaling: 10,
        powB1effect: 1,
        powB2effect: 1,
        powB3effect: 1,
        boosters: 0,
        boosterrequirement: 10 ** 9,
        boostereffect: 1,
        boosterbase: 2,
        boosterreq: [1, 10**300],
        BM1: false,
        BM2: false,
        BM3: false,
        miles: 0,
        bstrmiles: 0,
        bstrupgamnt: 0,
        boostupgcost: [3, 4, 5],
        BU1: false,
        BU2: false,
        BU3: false,
        BU1effect: 1,
        BU2effect: 1,
        BU3effect: 1,
        AutoAmount: 0,
        AutoGain: 0,
        PauseAuto: 0,
        PointAuto: 0,
        Presauto: 0,
        Powauto: 0,
        Autoauto: 0,
        autocost: [10, 1000, 10 ** 6, 10 ** 10],
        autoeff: [0, 0, 0, 0],
        QOLU: [false, false, false, false, false, false, false, false],
        QOLUBought: 0,
        AscAmount: 0,
        AscGain: 0,
        RankRequirement: [1, 2, 5, 15, 10 ** 300],
        RankEffect: ["Boost points by 10, Prestige by 5, Power by 3 and Ascension points by 2", "Keep 1 of each of the first three automations on ascension", "Unlock more Prestige upgrades and keep QOL I on Ascend", "Boost Ascension points based on Ranks and unlock some Ascension upgrades", "-"],
        RankLevel: 0,
        ifAscend: false,
        rank4reward: 1,
        rank4exp: 1,
        AscU1: false,
        AscU2: false,
        AscU3: false,
        ascupgamnt: 0,
        AscB1: [0, 1, 1, 1],
        APamount: [0, 0],
        APbuyables: [[0, 10 ** 28], [0, 10 ** 23], [0, 10 ** 20], [0, 100], [0, 10 ** 12]],
        APU: [[false, false, false, false], [false, false, false, false], [false, false, false, false], [false, false, false, false]],
        InVoid: false,
        BestPoints: 0,
        VoidEnergy: [0, 0, 1, 0],
        VoidPower: 0,
        VoidBuyables: [[0, 10], [0, 100], [0, [1000, 100000, 10 ** 300]]],
        VB3cost: [1000, 100000, 10 ** 300],
        VB3max: 2,
        VoidEffect: [1, 1, 1, 1],
        VoidBoosters: 0,
        VoidBoosterReq: 100000,
        ActiveVBAmount: 0,
        MaxVBAmount: 1,
        ActiveEffect: [false, false, false],
        VoidBooster1: [1, 1, 1, 0],
        VoidBooster2: [1, 0, 0, 0],
        VoidBooster3: [1, 1, 0, 1],
        VB3req: [1, 3, 6, 1000],
    };
    updateTabs();
};
